// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.commondef;

public enum EN_CLIENT_TYPE {

	CLIENT_NONE(0),
	CLIENT_APP(1),
	CLIENT_WEB(2),
	CLIENT_H5(3),
	CLIENT_WX_MINI(4);

	private final int value;

	private EN_CLIENT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static EN_CLIENT_TYPE convert(int value) {
		for(EN_CLIENT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
