// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.commondef;

public enum EN_USER_TYPE {

	USER_NONE(0),
	USER_UID(1),
	USER_WX_OPENID(11),
	USER_WX_UNIONID(12),
	USER_ALIPAY(21);

	private final int value;

	private EN_USER_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static EN_USER_TYPE convert(int value) {
		for(EN_USER_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
