// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.commondef;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class st_user_info {

	@TarsStructProperty(order = 0, isRequire = true)
	public int user_type = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String user_id = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String appid = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String access_token = "";

	public int getUser_type() {
		return user_type;
	}

	public void setUser_type(int user_type) {
		this.user_type = user_type;
	}

	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}

	public String getAppid() {
		return appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	public String getAccess_token() {
		return access_token;
	}

	public void setAccess_token(String access_token) {
		this.access_token = access_token;
	}

	public st_user_info() {
	}

	public st_user_info(int user_type, String user_id, String appid, String access_token) {
		this.user_type = user_type;
		this.user_id = user_id;
		this.appid = appid;
		this.access_token = access_token;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(user_type);
		result = prime * result + TarsUtil.hashCode(user_id);
		result = prime * result + TarsUtil.hashCode(appid);
		result = prime * result + TarsUtil.hashCode(access_token);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof st_user_info)) {
			return false;
		}
		st_user_info other = (st_user_info) obj;
		return (
			TarsUtil.equals(user_type, other.user_type) &&
			TarsUtil.equals(user_id, other.user_id) &&
			TarsUtil.equals(appid, other.appid) &&
			TarsUtil.equals(access_token, other.access_token) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(user_type, 0);
		_os.write(user_id, 1);
		_os.write(appid, 2);
		_os.write(access_token, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.user_type = _is.read(user_type, 0, true);
		this.user_id = _is.readString(1, true);
		this.appid = _is.readString(2, true);
		this.access_token = _is.readString(3, true);
	}

}
