// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.httpproto;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface HttpCGIPrx {

	public void get(st_cgi_req cgi_req, @TarsHolder Holder<st_cgi_rsp> rsp);

	public void get(st_cgi_req cgi_req, @TarsHolder Holder<st_cgi_rsp> rsp, @TarsContext java.util.Map<String, String> ctx);

	public void async_get(@TarsCallback HttpCGIPrxCallback callback, st_cgi_req cgi_req);

	public void async_get(@TarsCallback HttpCGIPrxCallback callback, st_cgi_req cgi_req, @TarsContext java.util.Map<String, String> ctx);
}
