// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.httpproto;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface HttpCGIServant {

	public void get(st_cgi_req cgi_req, @TarsHolder Holder<st_cgi_rsp> rsp);
}
