// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.httpproto;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class HttpCGIPrxCallback extends TarsAbstractCallback {

	public abstract void callback_get(st_cgi_rsp rsp);

}
