// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.account;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface AccessPrx {

	public void verify(st_token_verify_req req, @TarsHolder Holder<st_token_verify_rsp> rsp);

	public void verify(st_token_verify_req req, @TarsHolder Holder<st_token_verify_rsp> rsp, @TarsContext java.util.Map<String, String> ctx);

	public void async_verify(@TarsCallback AccessPrxCallback callback, st_token_verify_req req);

	public void async_verify(@TarsCallback AccessPrxCallback callback, st_token_verify_req req, @TarsContext java.util.Map<String, String> ctx);
}
