// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.account;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class AccessPrxCallback extends TarsAbstractCallback {

	public abstract void callback_verify(st_token_verify_rsp rsp);

}
