// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class st_token_verify_rsp {

	@TarsStructProperty(order = 0, isRequire = true)
	public int ret = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String msg = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public long uid = 0L;

	public int getRet() {
		return ret;
	}

	public void setRet(int ret) {
		this.ret = ret;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public long getUid() {
		return uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public st_token_verify_rsp() {
	}

	public st_token_verify_rsp(int ret, String msg, long uid) {
		this.ret = ret;
		this.msg = msg;
		this.uid = uid;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ret);
		result = prime * result + TarsUtil.hashCode(msg);
		result = prime * result + TarsUtil.hashCode(uid);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof st_token_verify_rsp)) {
			return false;
		}
		st_token_verify_rsp other = (st_token_verify_rsp) obj;
		return (
			TarsUtil.equals(ret, other.ret) &&
			TarsUtil.equals(msg, other.msg) &&
			TarsUtil.equals(uid, other.uid) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ret, 0);
		_os.write(msg, 1);
		_os.write(uid, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.ret = _is.read(ret, 0, true);
		this.msg = _is.readString(1, true);
		this.uid = _is.read(uid, 2, true);
	}

}
