// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.pxhua.video.proto.httpproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class st_cgi_req {

	@TarsStructProperty(order = 0, isRequire = true)
	public int mode = 1;
	@TarsStructProperty(order = 1, isRequire = true)
	public java.util.Map<String, String> query = null;
	@TarsStructProperty(order = 2, isRequire = true)
	public java.util.Map<String, String> cookie = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public com.pxhua.video.proto.commondef.st_user_info user_info = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public String client_ip = "";

	public int getMode() {
		return mode;
	}

	public void setMode(int mode) {
		this.mode = mode;
	}

	public java.util.Map<String, String> getQuery() {
		return query;
	}

	public void setQuery(java.util.Map<String, String> query) {
		this.query = query;
	}

	public java.util.Map<String, String> getCookie() {
		return cookie;
	}

	public void setCookie(java.util.Map<String, String> cookie) {
		this.cookie = cookie;
	}

	public com.pxhua.video.proto.commondef.st_user_info getUser_info() {
		return user_info;
	}

	public void setUser_info(com.pxhua.video.proto.commondef.st_user_info user_info) {
		this.user_info = user_info;
	}

	public String getClient_ip() {
		return client_ip;
	}

	public void setClient_ip(String client_ip) {
		this.client_ip = client_ip;
	}

	public st_cgi_req() {
	}

	public st_cgi_req(int mode, java.util.Map<String, String> query, java.util.Map<String, String> cookie, com.pxhua.video.proto.commondef.st_user_info user_info, String client_ip) {
		this.mode = mode;
		this.query = query;
		this.cookie = cookie;
		this.user_info = user_info;
		this.client_ip = client_ip;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mode);
		result = prime * result + TarsUtil.hashCode(query);
		result = prime * result + TarsUtil.hashCode(cookie);
		result = prime * result + TarsUtil.hashCode(user_info);
		result = prime * result + TarsUtil.hashCode(client_ip);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof st_cgi_req)) {
			return false;
		}
		st_cgi_req other = (st_cgi_req) obj;
		return (
			TarsUtil.equals(mode, other.mode) &&
			TarsUtil.equals(query, other.query) &&
			TarsUtil.equals(cookie, other.cookie) &&
			TarsUtil.equals(user_info, other.user_info) &&
			TarsUtil.equals(client_ip, other.client_ip) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(mode, 0);
		_os.write(query, 1);
		_os.write(cookie, 2);
		if (null != user_info) {
			_os.write(user_info, 3);
		}
		if (null != client_ip) {
			_os.write(client_ip, 4);
		}
	}

	static java.util.Map<String, String> cache_query;
	static { 
		cache_query = new java.util.HashMap<String, String>();
		String var_1 = "";
		String var_2 = "";
		cache_query.put(var_1 ,var_2);
	}
	static java.util.Map<String, String> cache_cookie;
	static { 
		cache_cookie = new java.util.HashMap<String, String>();
		String var_3 = "";
		String var_4 = "";
		cache_cookie.put(var_3 ,var_4);
	}
	static com.pxhua.video.proto.commondef.st_user_info cache_user_info;
	static { 
		cache_user_info = new com.pxhua.video.proto.commondef.st_user_info();
	}

	public void readFrom(TarsInputStream _is) {
		this.mode = _is.read(mode, 0, true);
		this.query = (java.util.Map<String, String>) _is.read(cache_query, 1, true);
		this.cookie = (java.util.Map<String, String>) _is.read(cache_cookie, 2, true);
		this.user_info = (com.pxhua.video.proto.commondef.st_user_info) _is.read(cache_user_info, 3, false);
		this.client_ip = _is.readString(4, false);
	}

}
